### ISSUE TITLE
s3 bucket updates

### ISSUE THREAD

**Issue by bukhosi-eugene-mpande** [COS301-SE-2024/ClassConnect#110]
# Working-On

s3 bucket updates for demo 3

## Description

- [x] picture upload
- [x] small 3D file upload
- [x] big 3D file upload
- [x] small pdf upload
- [x] big pdf upload
- [x] security checks on files uploaded
- [x] file conversion for unsupported 3D file formats

## Additional Information
- pictures will all have to less that 5mb
- there will be no size limit of pdf and 3D files
- the formats supported for pictures will be png, jpeg, webp
- the format supported for 3D images will be gtlf
- the format supported for lecture material will be PDF, PPTX and EPUB

**Comment by Ashley-Kapaso** [comment]
Is this issue done?
