### ISSUE TITLE
User Authorization

### ISSUE THREAD

**Issue by ayandajuqu** [COS301-SE-2024/ClassConnect#17]
Implement the backend functionality to authorize users based on roles (e.g., admin, lecturer, student). This should include middleware to protect routes and ensure only authorized users can access certain functionalities.

**Comment by Ashley-Kapaso** [comment]
Was this not apart of #15 ?

**Comment by ayandajuqu** [comment]
@Ashley-Kapaso It was, i decided to make it an issue by itself

**Comment by Ashley-Kapaso** [comment]
Oh okay.
