### ISSUE TITLE
Admin Fixes

### ISSUE THREAD

**Issue by Lunga-Ntando-Ndlovu** [COS301-SE-2024/ClassConnect#172]
# Working-On

## Description

- [x]  Need to add loading animation for CRUD operations.
- [x] For all the edit modals, the data needs to already be present
- [x]  For all edit modals, the error needs to be fixed for image
- [x] When creating an organisation and choosing a file for the logo, the following needs to be changed: Feedback for when a user does not input the correct filetype, and there needs to be feedback if the image size is too big.

## Additional Information

[Any additional details or context that might be helpful.]

**Comment by Ashley-Kapaso** [comment]
Image upload error is fix, just need feedback functionality
