### ISSUE TITLE
Live Session

### ISSUE THREAD

**Issue by JoshuaTristanWereley** [COS301-SE-2024/ClassConnect#47]
**Description**
Create functionality for a virtual classroom, that allows lecturers to create lessons and students to join the lesson. It should also allow the lecturer to share tier screen.

- [x] **Create Lesson**: Allow the lecture to schedule a lesson and share to students
- [x] **Join Lesson:** Allow students to join the lesson
- [x] **Screen Sharing**: Allow lectures to share their screen

**Comment by Ashley-Kapaso** [comment]
Done.
