### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by JoshuaTristanWereley** [COS301-SE-2024/ClassConnect#52]
# Working-On

## Description

- [ ] Update README.md (Links To Demo 2 Stuff, Update Styling)
- [ ] Complete Architectural Diagram
- [ ] Update Use Case Diagram/s
- [ ] Update UML Class Diagram
- [ ] Update SRS
- [ ] Technical install doc
- [ ] User manual
- [ ] Tech req
- [x] Coding Standards

**Comment by Ashley-Kapaso** [comment]
@JoshuaTristanWereley Are all these tasks done?
