### ISSUE TITLE
Admin Page 

### ISSUE THREAD

**Issue by bukhosi-eugene-mpande** [COS301-SE-2024/ClassConnect#96]
# Working-On

## Description

Refactoring of the admin page

## Additional Information / checklist

- [x] New organisation page
- [x] Update organisations backend
- [x] New Topbar 
- [x] New Sidebar 
- [x] New icons pack
- [x] New lecturers page // Ayanda and Ashley
- [x] New Students page // Ayanda and Ashley
- [x] New Admins page // Ayanda and Ashley
- [x] New workspaces page // Ayanda and Ashley
- [x] Combined activities and announcements page //Ayanda
- [ ] Tests for the admin page
- [ ] Profile page

**Comment by Ashley-Kapaso** [comment]
Is this issue complete?
